[server]
headless = true
enableCORS = false
enableXsrfProtection = true
port = 8501

[browser]
gatherUsageStats = false

[theme]
base="light"
primaryColor="#4a90e2"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f2f2f2"
textColor="#000000"
